# This file was generated by GoReleaser. DO NOT EDIT.
cask "elevator" do
  version "5.0.0"

  on_macos do
    on_arm do
      sha256 "3cef2a230139a17a553dc6d37f75d1673f58f3cfbc01b31ec9e9c19388db20ae"
      url "https://github.com/fivexl/terraform-aws-sso-elevator/releases/download/#{version}/elevator-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "085883dbbd1af0da631bd6a6a1f78b971e81fcc52ae8e9399132d285983e3189"
      url "https://github.com/fivexl/terraform-aws-sso-elevator/releases/download/#{version}/elevator-darwin-amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ea890e716b52286d4aef8ce3784aebad8df4bad7216ad2ecaa191b658dea800d"
      url "https://github.com/fivexl/terraform-aws-sso-elevator/releases/download/#{version}/elevator-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "f072719da0e27ef397c0e92662bd6d8edeb80451f7053bc9d015cee6128bf967"
      url "https://github.com/fivexl/terraform-aws-sso-elevator/releases/download/#{version}/elevator-linux-amd64.tar.gz"
    end
  end

  name "elevator"
  desc "Submit temporary AWS access requests from the command line"
  homepage "https://github.com/fivexl/terraform-aws-sso-elevator"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "elevator"

  # No zap stanza required
end
