# This file was generated by GoReleaser. DO NOT EDIT.
cask "elevator" do
  version "4.4.3"

  on_macos do
    on_arm do
      sha256 "9fb49ca0f93740290066ef559ef039d866d800d9823b6ccca220d3a8838d4c84"
      url "https://github.com/fivexl/terraform-aws-sso-elevator/releases/download/#{version}/elevator-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "582db01a3eeff4fbf3bb6a0f9328395d434cef24791be534ed6793befb09fe37"
      url "https://github.com/fivexl/terraform-aws-sso-elevator/releases/download/#{version}/elevator-darwin-amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1f12349dc72bafd6f1e9d050e96f62387555e788bf9baeeb9d6053feca60c898"
      url "https://github.com/fivexl/terraform-aws-sso-elevator/releases/download/#{version}/elevator-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "848cf0b026650dd4f176014a9468a2e3867bd383a20e58f66d2237e34e3aa4fc"
      url "https://github.com/fivexl/terraform-aws-sso-elevator/releases/download/#{version}/elevator-linux-amd64.tar.gz"
    end
  end

  name "elevator"
  desc "Submit temporary AWS access requests from the command line"
  homepage "https://github.com/fivexl/terraform-aws-sso-elevator"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "elevator"

  # No zap stanza required
end
