# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Elevate < Formula
  desc "Submit temporary AWS access requests from the command line"
  homepage "https://github.com/fivexl/terraform-aws-sso-elevator"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fivexl/terraform-aws-sso-elevator/releases/download/v0.1.0/elevate-darwin-amd64.tar.gz"
      sha256 "447a7cfcd843eb76f2cdbe61bd22d7b5936e31f72e35b84a90f59b64edfa383b"

      define_method(:install) do
        bin.install "elevate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fivexl/terraform-aws-sso-elevator/releases/download/v0.1.0/elevate-darwin-arm64.tar.gz"
      sha256 "d8d85708c591ef11f7b62292913886924e9901a869f1783137ef33061fcf1cfc"

      define_method(:install) do
        bin.install "elevate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fivexl/terraform-aws-sso-elevator/releases/download/v0.1.0/elevate-linux-amd64.tar.gz"
      sha256 "561617be6bf752ec02bca27a642e80cbb7b1a3e8bfdd5458dd0a53904f3fa917"
      define_method(:install) do
        bin.install "elevate"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fivexl/terraform-aws-sso-elevator/releases/download/v0.1.0/elevate-linux-arm64.tar.gz"
      sha256 "e692c63d5abf4ebfb18e7425d9b65655ad08bf8ab86dd83bd32b39487b78ae1d"
      define_method(:install) do
        bin.install "elevate"
      end
    end
  end

  test do
    system "#{bin}/elevate", "version"
  end
end
